version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing dependency...
      - npm install next -g
  pre_build:
    commands:
      - printenv > .env
  build:
    commands:
      - npx next build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
    
