version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - next build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - buildspec.yml
    - appspec.yml
    - components/Account.js
    - components/Auth.js
    - pages/_app.js
    - pages/index.js
    - pages/api/hello.js
    - public/favicon.ico
    - public/vercel.svg
    - styles/Home.module.css
    - styles/global.css
    - utils/supabaseClient.js
    - .eslintrc.json
    - next.config.js
    - package-lock.json
    - package.json
    
    
